name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Build all code and images using make
      run: make

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set lowercase repository name
      id: repo_name_lower
      run: echo "repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

    - name: Tag Docker image for GitHub Container Registry
      run: |
        docker tag openscad/wasm-release ghcr.io/${{ steps.repo_name_lower.outputs.repo_name }}:latest

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ steps.repo_name_lower.outputs.repo_name }}:latest